apiVersion: v1
kind: Service
metadata:
  name: nexusai-pricing
  labels:
    app: nexusai-pricing
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nexusai-pricing
